import "../styles/globals.css";
import StoreNavigation from "../components/storeNavigation";
import FooterSection from "../components/footer";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["cyrillic"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreNavigation />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
