// import "../styles/globals.css";
// import StoreNavigation from "../components/storeNavigation";
// import FooterSection from "../components/footer";

// import { Roboto } from "next/font/google";

// const roboto = Roboto({
//   subsets: ["cyrillic"],
//   variable: "--font-roboto",
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={roboto.className}>
//         <StoreNavigation />
//         {children}
//         <FooterSection />
//       </body>
//     </html>
//   );
// }

import "@/styles/globals.css";
import StoreNavigation from "@/components/storeNavigation";
import FooterSection from "@/components/footer";

import { Roboto } from "next/font/google";
import { getCategories } from "@/services/productService";

const roboto = Roboto({
  subsets: ["cyrillic"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 🧠 ВЗИМАМЕ подкатегориите на категория с ID 17 (Artdeco ASIAN SPA)
  // const res = await fetch(
  //   "https://nardis.rosset.website/wp-json/wc/v3/products/categories?parent=17",
  //   {
  //     headers: {
  //       Authorization:
  //         "Basic " +
  //         Buffer.from(
  //           `${process.env.WC_CONSUMER_KEY}:${process.env.WC_CONSUMER_SECRET}`
  //         ).toString("base64"),
  //     },
  //     next: { revalidate: 60 }, // SSR + кеширане за 60 секунди
  //   }
  // );
  // NEW with all cats and subcats
  // В layout.js, замени fetch-а със следното:
  const res = await fetch(
    "https://nardis.rosset.website/wp-json/wc/v3/products/categories?per_page=100",
    {
      headers: {
        Authorization:
          "Basic " +
          Buffer.from(
            `${process.env.WC_CONSUMER_KEY}:${process.env.WC_CONSUMER_SECRET}`
          ).toString("base64"),
      },
      next: { revalidate: 60 },
    }
  );

  const allCategories = await res.json();

  // Групиране на категории по parent-child
  const parentCategories = allCategories.filter((cat) => cat.parent === 0);
  const categoriesWithChildren = parentCategories.map((parent) => {
    const children = allCategories.filter((cat) => cat.parent === parent.id);
    return {
      ...parent,
      subcategories: children,
    };
  });

  // const subcategories = await res.json();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreNavigation categories={categoriesWithChildren} />

        {children}
        <FooterSection />
      </body>
    </html>
  );
}
